# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"var": "00_nb1.ipynb",
         "var2": "01_nb2.ipynb"}

modules = ["my_module.py"]

doc_url = "https://GilesStrong.github.io/nbdev_test/"

git_url = "https://github.com/GilesStrong/nbdev_test/tree/master/"

def custom_doc_links(name): return None
