# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"var2": "00_regression_data.ipynb",
         "var": "01_data.ipynb"}

modules = ["data.py"]

doc_url = "https://GilesStrong.github.io/nbdev_test/"

git_url = "https://github.com/GilesStrong/nbdev_test/tree/master/"

def custom_doc_links(name): return None
